### ISSUE TITLE
[Bug] [Causes Crash] Removal of hammer recipes does not work

### ISSUE THREAD

**Issue by SnowShock35** [jaredlll08/ModTweaker2#112]
Hi Jared,

So it seems the hammer support for ex-nihilo refuses to work when removing hammer recipes. 
Here is some more detail on the bug...

MC: 1.7.10
Forge: 1291 (rec at time)
MineTweaker: 3.0.9 (Also tried 3.0.9c)
ModTweaker2: 0.7.5
Crash report: http://paste.ee/p/8dQpb

Description: 

Basically what is happening is I add the to the script the bellow text to remove any item (in this case it was Ex-Nihilo Crushed Netherrack) I then do /mt reload it says script reloaded. However, if I try and look up the recipe it will crash and give the above crash report (Repeatable).

Example:
mods.exnihilo.Hammer.removeRecipe(<exnihilo:exnihilo.gravel_nether>);

**Comment by Turkey2349** [comment]
This should be fixed. If not let me know.

**Comment by Yulife** [comment]
Open the issue if the bug still persists :)

**Comment by SnowShock35** [comment]
It might be fixed but there is no release so it's technically not fixed my end :/

**Comment by Dream-Master** [comment]
With a small knowledge of Gradle you can fork the project and rebuild it by your self. 
(using cmd command "gradlew build" without the "" ) in the folder where your github Fork is.

**Comment by jaredlll08** [comment]
last I checked I released the version

**Comment by SnowShock35** [comment]
@jaredlll08 I saw that after first posting this, thx Jared ;)

**Comment by Yulife** [comment]
You should rather thank @;)urkey2349

**Comment by SnowShock35** [comment]
Okies, well thanks @Turkey2349 ;)

**Comment by SnowShock35** [comment]
Hmm Seems to be giving this error. https://imgur.com/a/Zsa34 that's what I used mods.exnihilo.Hammer.removeRecipe(exnihilo:exnihilo.gravel_nether);

**Comment by Turkey2349** [comment]
There shouldn't be a need for the second exnihilo after exnihilo: , also mind posting line 29 of that script?
